os: linux
language: c++



matrix:
  include:
    - os: linux
      dist: focal
      services: docker
    - os: osx
      services: docker
      osx_image: xcode12.2


compiler:
  - clang


before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker build -t testimage . ; fi



script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker run testimage /bin/bash -c "cd /test/app; ./build.py --clean -tests" ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./build.py --clean -tests ; fi
