image:
- Visual Studio 2019
environment:
  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    - PYTHON: "C:\\Python39-x64"
  
install:
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install conan
  - pip install parameterized
  - pip install gcovr
  - where gcc
  
build: off


test_script:
    - cd buildSystemTests && python runTests.py
