image:
- Visual Studio 2019
environment:
  matrix:
    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    - PYTHON: "C:\\Python39-x64"
  
install:
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\;%PATH%
  - pip install conan
  - pip install parameterized
  - pip install gcovr
  - where gcc
  
build: off


test_script:
    - cd buildSystemTests && python runTests.py
