image:
- Visual Studio 2019
environment:
  matrix:
  - TOXENV: py37
  
install:
  - pip install conan
  - pip install parameterized
  - pip install gcovr
  
build: off


test_script:
    - cd buildSystemTests && python3 runTests.py
